# 原生类

BuiltinClassOrig = [
    'stdClass',
    'Exception',
    'ErrorException',
    'Error',
    'CompileError',
    'ParseError',
    'TypeError',
    'ArgumentCountError',
    'ArithmeticError',
    'DivisionByZeroError',
    'Closure',
    'Generator',
    'ClosedGeneratorException',
    'WeakReference',
    'DateTime',
    'DateTimeImmutable',
    'DateTimeZone',
    'DateInterval',
    'DatePeriod',
    'HashContext',
    'JsonException',
    'LogicException',
    'BadFunctionCallException',
    'BadMethodCallException',
    'DomainException',
    'InvalidArgumentException',
    'LengthException',
    'OutOfRangeException',
    'RuntimeException',
    'OutOfBoundsException',
    'OverflowException',
    'RangeException',
    'UnderflowException',
    'UnexpectedValueException',
    'RecursiveIteratorIterator',
    'IteratorIterator',
    'FilterIterator',
    'RecursiveFilterIterator',
    'CallbackFilterIterator',
    'RecursiveCallbackFilterIterator',
    'ParentIterator',
    'LimitIterator',
    'CachingIterator',
    'RecursiveCachingIterator',
    'NoRewindIterator',
    'AppendIterator',
    'InfiniteIterator',
    'RegexIterator',
    'RecursiveRegexIterator',
    'EmptyIterator',
    'RecursiveTreeIterator',
    'ArrayObject',
    'ArrayIterator',
    'RecursiveArrayIterator',
    'SplFileInfo',
    'DirectoryIterator',
    'FilesystemIterator',
    'RecursiveDirectoryIterator',
    'GlobIterator',
    'SplFileObject',
    'SplTempFileObject',
    'SplDoublyLinkedList',
    'SplQueue',
    'SplStack',
    'SplHeap',
    'SplMinHeap',
    'SplMaxHeap',
    'SplPriorityQueue',
    'SplFixedArray',
    'SplObjectStorage',
    'MultipleIterator',
    'ReflectionException',
    'Reflection',
    'ReflectionFunctionAbstract',
    'ReflectionFunction',
    'ReflectionGenerator',
    'ReflectionParameter',
    'ReflectionType',
    'ReflectionNamedType',
    'ReflectionMethod',
    'ReflectionClass',
    'ReflectionObject',
    'ReflectionProperty',
    'ReflectionClassConstant',
    'ReflectionExtension',
    'ReflectionZendExtension',
    'ReflectionReference',
    'SessionHandler',
    '__PHP_Incomplete_Class',
    'php_user_filter',
    'Directory',
    'AssertionError',
    'ZipArchive',
    'LibXMLError',
    'DOMException',
    'DOMStringList',
    'DOMNameList',
    'DOMImplementationList',
    'DOMImplementationSource',
    'DOMImplementation',
    'DOMNode',
    'DOMNameSpaceNode',
    'DOMDocumentFragment',
    'DOMDocument',
    'DOMNodeList',
    'DOMNamedNodeMap',
    'DOMCharacterData',
    'DOMAttr',
    'DOMElement',
    'DOMText',
    'DOMComment',
    'DOMTypeinfo',
    'DOMUserDataHandler',
    'DOMDomError',
    'DOMErrorHandler',
    'DOMLocator',
    'DOMConfiguration',
    'DOMCdataSection',
    'DOMDocumentType',
    'DOMNotation',
    'DOMEntity',
    'DOMEntityReference',
    'DOMProcessingInstruction',
    'DOMStringExtend',
    'DOMXPath',
    'PDOException',
    'PDO',
    'PDOStatement',
    'PDORow',
    'SimpleXMLElement',
    'SimpleXMLIterator',
    'XMLReader',
    'XMLWriter',
    'CURLFile',
    'finfo',
    'mysqli_sql_exception',
    'mysqli_driver',
    'mysqli',
    'mysqli_warning',
    'mysqli_result',
    'mysqli_stmt',
    'PharException',
    'Phar',
    'PharData',
    'PharFileInfo',
]

BuiltinClass = dict()
for cl in BuiltinClassOrig:
    BuiltinClass["\\"+cl] = {}

BuiltinClass["\\SplFileInfo"]["!construct_tostr"] = 1

# 记录内置类的继承关系，注意这里不包括接口实现，接口实现在内置接口中处理
BuiltinClassExt = {
    "\\RecursiveArrayIterator": "\\ArrayIterator",
    "\\SplFileObject": "\\SplFileInfo",
    "\\SplTempFileObject": "\\SplFileObject",
    "\\DirectoryIterator": "\\SplFileInfo",
    "\\FilesystemIterator": "\\DirectoryIterator",
    "\\RecursiveDirectoryIterator": "\\FilesystemIterator",
}
